# -*- mode: Python; -*- scons script

## @file web/SConscript
#  @brief scons build for server part (Python django)

import os, platform, re, shutil

Import('env')


out_dir = '../build_web/'
#file_ver_name = out_dir + 'version/version_gen.py'
#env.Command(file_ver_name, [], build_websrv_version )

#install web
app_src = '../web'
for root, dirs, files in os.walk(app_src):
   p = os.path.relpath(root, app_src) #relative path
   for name in files:
      filename = os.path.join(root, name)
      inst_file = env.Install(out_dir + p, filename)
      if re.match('.*\.py$', filename):
         pyc = env.File( str(filename) + 'c' )
         env.SideEffect( pyc, inst_file)


env.Clean('.',out_dir)

